### ISSUE TITLE
Update a preview version to crates.io.

### ISSUE THREAD

**Issue by MiyakoMeow** [jerry73204/apriltag-rust#6]
I'm now using this respository directly as dependency. It's now usable for me, while I just use tags' corners.
[The version in crates.io](https://crates.io/crates/apriltag) is old, using the old version of [apriltag-sys](https://crates.io/crates/apriltag-sys).
If I directly follow the guide in `apriltag-sys`, then use the latest version of `apriltag` on crate.io, it will not work on windows.
Because the latest version of `apriltag-sys` is 0.2, but the latest version of `apriltag` is now using `apriltag-sys` 0.1.5.
You can update a preview version to crates.io to solve this.
Thanks!

**Comment by jerry73204** [comment]
This crate is extensively rewritten and is published to crates.io now. Please enjoy it.
