### ISSUE TITLE
Request for natively converting poses' matrices into nalgebra structs

### ISSUE THREAD

**Issue by gautvm** [jerry73204/apriltag-rust#9]
Hi there,

I was wondering if there are any plans to convert poses' rotation and translation matrices into nalgebra structs? I've been using the library for a project, but I've been struggling to find a dependable solution that produces the correct rotation matrix every time. It would be great if this could be a built-in feature. I know there was a previous issue on this topic, but it was from a while back.

By the way, great work on this!

**Comment by jerry73204** [comment]
The conversion part is moved to [apriltag-nalgebra](https://docs.rs/apriltag-nalgebra/). There are reasons to have a separate crate. Nalgebra bumps its version frequently. Also, in some cases nalgebra is not needed. The separation avoids the bloating issue.

**Comment by gautvm** [comment]
That works, thank you.
